### ISSUE TITLE
Match? Icon

### ISSUE THREAD

**Issue by jongleur1983** [sozialhelden/poichecker#2]
Das Match-Icon in der Kandidatenliste sieht mit dem Haken so aus, als würde man bereits bestätigen. Fand ich zunächst schwierig, weil ich nicht wusste, ob es zusammenpasst. 
Evtl. Icon verändern.

**Comment by jongleur1983** [comment]
Kann es sein, dass ihr das Icon jetzt durch text ersetzt habt? dann wäre dieses Ticket eigentlich erledigt, oder?

**Comment by holgerd** [comment]
ja, du hast recht. heisst nun "der ist es" statt eines symbols. der button führt dann zur matching-detailseite.
